### ISSUE TITLE
BUG: bgm trava na transição de uma cena para outra

### ISSUE THREAD

**Issue by nawarian** [tecMTST/pororoca-terminal#106]
## Descrição do problema

Na transição do menu principal para o mini-game o som fica dá um glitch.

### Vídeo / Imagem

https://github.com/user-attachments/assets/589dea37-ee12-4979-b611-d43fb6ed9dfa

## Comportamento esperado

* Transição suave entre uma cena e outra
* Som sem travamentos

## Plataformas

O teste foi realizado nestas plataformas:

* [ ] Windows / Google Chrome
* [ ] Windows / Mozilla Firefox
* [ ] Windows / Microsoft Edge
* [x] Linux / Mozilla Firefox
* [x] Linux / Google Chrome
* [ ] Android / Mozilla Firefox
* [x] Android / Google Chrome
* [ ] MacOSx / Google Chrome
* [ ] MacOSx / Safari
* [ ] MacOSx / Mozilla Firefox
* [ ] iOS / Safari
* [ ] iOS / Google Chrome

**Comment by mihailov-vf** [comment]
Esse bug pude perceber testando localmente também e acredito que tem a ver com o loading dinâmico que estamos fazendo dentro da cena no momento de gerar os obstáculos.

Acredito que alterar para onde pudermos fazer preload e carregamento de assets na inicialização da cena resolva isso.

**Comment by mihailov-vf** [comment]
@albertoneto, @nawarian.
Tivemos uma melhoria considerável após um refactor com foco na performance pra Web.
Este e o #137 estão contemplados.
